### ISSUE TITLE
Is it possible to lazy load multiple components in the same module?

### ISSUE THREAD

**Issue by JosephChotard** [brunob15/ngx-element#25]
I'm trying to load multiple components in the same module but I'm not sure how to do this. Is it possible?

**Comment by patrickglasgow** [comment]
Currently the selector used for the component is defined at the module level so only one component per module can be registered.

However, by using a monorepo structure (nx) you can have one 'core' module which hosts all of your components then wrap each component you want to expose as an ngx-element in a 'presentation' module. This would allow many components from the same module to be exposed - you would lose some of the benefits of the lazy loading by doing this since when one component is used it would load almost everything.

You may want to consider if you can restructure your project into more modules, if you want component 'a' from your 'core' module do you really want components 'b' and 'c' to be loaded.

**Comment by JosephChotard** [comment]
ok great, thank you for letting me know! I have a quick follow up. Will ngx-element load the element multiple times if it's used multiple times on the same page? (I'm asking this because angular-extensions/elements only loads each element the first time it's called)

**Comment by patrickglasgow** [comment]
I'm almost certain that the js module will only be loaded once as once it's there it will use the existing one.

You can test this pretty easily by putting 2 components on your page as watching the network to see which files are loaded and when. You should only see one download of the module containing your component even though it is rendered on your page twice.

**Comment by brunob15** [comment]
Hi guys, thanks for this conversation.

@JosephChotard could you elaborate on what is your use case? Maybe it could be an enhacement to the library depending on what you want to achieve.

And @patrickglasgow is right. The module will be downloaded only one time at the beginning and you can add any amount of instances of your component to the page.

**Comment by brunob15** [comment]
By the way, can I ask you how did you find this library? @patrickglasgow @JosephChotard

**Comment by patrickglasgow** [comment]
I'm enjoying it, I found it reading your articles I was partially starting to write my own helper or component which would do exactly as you have done.

I'm still trying to integrate it fully as I convert my existing angular library into a web component library.

Right now I'm having a problem getting the injector to be available, I know that you are injecting it into the ngx-element:

`  constructor(private injector: Injector) {
    const ngxElement = createCustomElement(NgxElementComponent, { injector });
    customElements.define('ngx-element', ngxElement);
  }`

But I'm having the issue where it's not available in my sub component?

My example is that:

`constructor(
    private cdRef: ChangeDetectorRef
  ) {
    super();
  }`

but I get the error Error: Can't resolve all parameters for TestInjectionComponent: (?).

I know it is possible with angular/elements from watching this: https://www.youtube.com/watch?v=Z1gLFPLVJjY&t=4s

Just struggling to know how to combine it with ngx-element

Any advice you could give on this would be really appreciated (happy to chat elsewhere or in a more appropriate issue)?

Great work though really enjoy this library, Thank you for building it.

**Comment by brunob15** [comment]
@patrickglasgow did you try sharing the injector via a service?

**Comment by JosephChotard** [comment]
Thank you even though your library is very useful I decided to go with a custom approach built with the help of Manfred Steyer who showed me how to lazy load entire modules from within angular elements.

As for how I find your library, I was scrolling through google and found this page which has a clear README and seemed to do something similar to what I wanted. Thank you for building this library!

**Comment by patrickglasgow** [comment]
> @patrickglasgow Thanks for your feedback! Did you try sharing the injector via a service?

Sorry after more investigation this was not an error with this package, simply with our approach to packaging up our module as a web-component library and trying to consume it in a react application. We now are bundling it as an application to ensure we have renderer2 and changedetectionref available at runtime.
