### ISSUE TITLE
What is the best way to get events invoked by @Output()?

### ISSUE THREAD

**Issue by mlc-mlapis** [brunob15/ngx-element#27]
There is no mention of the opposite way to `@Input()` -> `@Output()`. The `<ngx-element>` is a wrapper for an inner instance of a component so to register an event on that wrapper as `addEventListener()` has no effect.

**Comment by brunob15** [comment]
Hi @mlc-mlapis, currently there is no way of handling events triggered with `@Output`. It is one of the main missing features for now.

Feel free to open a PR to add that functionality to the library if you want!

Thank you,
Bruno.

**Comment by mlc-mlapis** [comment]
[**@brunob15**](https://github.com/brunob15) OK, I'll think about the best way how to do it.

**Comment by patrickglasgow** [comment]
@mlc-mlapis In my solution using ngx-element I use an event bus which can be scoped to component or to all events of that type to handle the output events from anywhere it is required. I've found this pattern a lot more flexible than using the @Output events angular pattern, maybe something to consider :)

**Comment by mlc-mlapis** [comment]
[**@patrickglasgow**](https://github.com/patrickglasgow) Yep, I understand what you mean, but in my case, the problem is to separate some parts of the Angular application version 5, implement them in the lastest environment of the Nx monorepo and reuse them back as web components in that old application, so `@Input()` and `@Output()` is the crucial compatibility requirement.

**Comment by patrickglasgow** [comment]
@mlc-mlapis That makes sense.

Are you running angular in your NX monorepo project?

**Comment by mlc-mlapis** [comment]
[**@patrickglasgow**](https://github.com/patrickglasgow) Exactly.

**Comment by patrickglasgow** [comment]
@mlc-mlapis  You will have some performance issues with running 2 versions of angular. But I guess this is weighted against you having to invest in upgrading your angular 5 project?

**Comment by mlc-mlapis** [comment]
**@patrickglasgow** You think in the right direction. That Angular 5 application is not using Angular CLI, but some custom building ways, so it's even more complicated to migrate it directly to the latest. So the idea is to minimize it to the outer shell by separating inner parts and in the final step migrate only that shell app to the latest Nx infrastructure and then use already native and latest parts.

**Comment by brunob15** [comment]
I think this might help as inspiration @mlc-mlapis: https://medium.com/angular-in-depth/how-angular-elements-uses-custom-events-mechanism-to-transmit-components-outputs-outside-angular-7b469386f6e2

**Comment by mlc-mlapis** [comment]
**@brunob15** Exactly. I have already gone through the available resources, including this one. Actually, it looks like adding new binding syntax to instruct `<ngx-element>` what are the expected outputs that should be proxied from an inner component to the outer one. Probably the bad news is the fact it's not possible dynamically create `@Output()` on  `<ngx-element>` level (and expect the automapping from Angular Elements), so it's necessary to do that a little blindly. Finally, some unit tests can help with cross-checking, plus the possibility of linting rules.

**Comment by mlc-mlapis** [comment]
**@**[**brunob15**](https://github.com/brunob15) **@patrickglasgow** I added a new PR that uses the same logic as Angular Elements for bridging all outputs from an inner dynamic component instance to the outer web component. It works fine. Look at it.

**Comment by mlc-mlapis** [comment]
@brunob15

I added a new PR that introduces a real example of the new functionality (listening to emits of Angular component outputs).

I probably also explained why you had a problem with running it. See the comment in the PR. Try to run the app demo example. It works on my side. It would be nice to hear the same from your side also.

Thanks.
