### ISSUE TITLE
Question reg. PR's

### ISSUE THREAD

**Issue by michaelkrog** [brunob15/ngx-element#33]
Hi.
I hope it is okay to post a question here reg. PR's.

We want to contribute to your project during our next sprint or two. The things we are lacking and will make PR's for are these in particular:

* casing conversion from html attributes to component properties
* slot / ngContent support

Would you accept PR's for the mentioned?

**Comment by brunob15** [comment]
Hi @michaelkrog.
For sure the contributions will be accepted. I will be also dedicating some time to the library in the next few weeks.

I have a couple of questions:
- Could you elaborate on what are your needs regarding _casing conversion from HTML attributes to component properties_?
- Do you currently have any approach to tackle content projection support?

Thank you!

**Comment by michaelkrog** [comment]
Hi Bruno.

Remark: We've cloned your project a few months back, so some of it may already be fixed in your repo. 

**Casing**
One or our developers reported that the [mapping of properties](https://angular.io/guide/elements#mapping) does not always work correct. Fx. `@Input() inputProp` we should be able set as `input-prop` attribute via the HTML-tag. According to the report I got, it does not work.

**Content Projection**
We currently havent looked into an approach, but we will during our next sprint. We use a combination of StencilJS (our design system components) and Angular (our smart components) and we strive for the Angular components to have lazy-loading support on par with Stencil. The lack of content projection is the most important issue for us right now.

**Comment by brunob15** [comment]
Currently, you can pass properties to your component only via data-attributes. For example, to set your `inputProp` property you should do the following: `<ngx-element selector="..." data-input-prop="value">`.

Ok then, looking forward to what you come up with to tackle the content projection support :)

Thank you!

**Comment by michaelkrog** [comment]
We had to create a copy of the project instead of a fork, because of the way we maintain and build our projects. Also we have some requirements to this project that you may or may not like to get into your repo.

This is what we have added so far.

### Support for native custom element tag names
The way ngx-element requires an element to be registered is `<ngx-element select="talk" data-property="..."`, but what we need is a more standard custom element approach like `<app-talk property="..."`. We have added support for that, together with configuration for switching between one or the other way of registering the components.

Todo that we have added a registry that holds the details and inject that in constructors instead of a list with LazyComponentDef:
```Javascript
export interface LazyComponentRegistry {
  /** A list of LazyComponentDef for this registry. */
  definitions: LazyComponentDef[];
  /** Whether this uses native custom element tag names or a selector attribute. */
  useCustomElementNames: boolean;
  /** If useCustomElementNames is true, then this specifies the REQUIRED prefix for the tag names according to Custom Element specification. */
  customElementNamePrefix?: string;
}
```

### Less verbose config
We are going to have a lot of components registered over time, so we would like to have a less verbose configuration. We have added a simple method for this which helps just a bit with that, although we are stilling looking for ways to trim it.

The way we configure it now is like this:
```
createDef('talk', () => import('./talk/talk.module').then(m => m.TalkModule)) 
```

### Content Projection
We have added support for content projection. This was done by adding an `<ng-content>` to NgxElementComponent's template and manually finding the elements in lists that can be added as projectedNodes when calling `container.createComponent`.

--------

Do you think that all of the above is something you would like PR's for? 
(I will need to cherry-pick to make PR's, so if you can pinpoint what you would like, that would make my cherrypicking easier) :smile:
